name: test


on:
  push:
    branches:
      - master


jobs:
  testing:

    runs-on: ubuntu-latest
    steps:

    - name: user
      uses: actions/checkout@v1 

    - name: dir_check
      run: ls -la




 
