

name: MegaLenya


on:
  push:
    branches: 
     - master
  



 


jobs:
  noname:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: user
      uses: actions/checkout@v1
      
    - name: dir_check
      run: ls -la
      


 
